#!/bin/sh -e
usage="Usage: $(basename $0) OUTPUT PACKAGE..."
shorthelp=\
"Create an iso image containing a debian archive named \"archive\"
containing PACKAGEs."
help=\
"Miscellaneous notes:
 * The dist is \"master\"
 * The component name is name \"main\""

test $# -ge 2 || { echo -e "$usage\n$shorthelp\n\n$help" >&2; exit 1; }
OUTPUT=$1; shift
test ! -e $OUTPUT || { echo "Error: refusing to overwrite $OUTPUT"; exit 1; }
PACKAGES=$@
DIST=master

init_archive () {
	archive=$1
	mkdir -p $archive/conf
	cat >$archive/conf/distributions <<-END
	Codename: $DIST
	Components: main
	Architectures: source armhf armel amd64 mips
	END
}

add_packages () {
	archive=$1; shift
	packages=$@
	reprepro -b $archive includedeb $DIST $packages
}

exec >/dev/null
temp_archive=$(mktemp -d --tmpdir $(basename $0).XXXXXXXXXX)/archive
trap "rm -rf $temp_archive" EXIT
init_archive $temp_archive
add_packages $temp_archive $PACKAGES
genisoimage -quiet -o $OUTPUT -V "APT package source" -r \
	$(dirname $temp_archive)
