#!/bin/sh -e
usage="Usage: $(basename $0) [-i PACKAGE] OUTPUT [PACKAGE...]"
shorthelp=\
"Create an iso image containing a debian archive named \"archive\"
containing PACKAGEs."
help="\
Options:
 -i PACKAGE  Install PACKAGE by forcing it into section \"auto-install\".
             May be repeated to install multiple packages.

Notes:
 * The dist is named \"master\"
 * The component is named \"main\""

fail ()
{
	if [ -n "$1" ]; then
		msg="$1"
	else
		msg="$usage\n$shorthelp\n\n$help"
	fi

	echo "$msg" >&2
	exit 1
}

while [ "$#" -gt 0 ]; do
case "$#,$1,$2" in
	*,-i,?*)
		install="$install $2"
		shift
		shift
		;;

	*,-*,*)
		fail
		;;

	*,*,*)
		if [ -z "$output" ]; then
			output=$1
		else
			main="$main $1"
		fi
		shift
		;;
esac
done

test -n "$output" || fail
test ! -e $output || fail "Error: refusing to overwrite $output"
test -n "$install$main" || fail

dist=master

init_archive () {
	archive=$1
	mkdir -p $archive/conf
	cat >$archive/conf/distributions <<-END
	Codename: $dist
	Components: main
	Architectures: source armhf armel amd64 mips
	Label: Pragmatux
	END
}

add_main_packages () {
	_archive=$1; shift
	_packages=$@
	reprepro -b $_archive includedeb $dist $_packages
}

add_install_packages () {
	_archive=$1; shift
	_packages=$@
	reprepro -b $_archive --section auto-install includedeb $dist $_packages
}

exec >/dev/null
temp_archive=$(mktemp -d --tmpdir $(basename $0).XXXXXXXXXX)/archive
trap "rm -rf $(dirname $temp_archive)" EXIT
init_archive $temp_archive
test -n "$main" && add_main_packages $temp_archive $main
test -n "$install" && add_install_packages $temp_archive $install
genisoimage -quiet -o $output -V "APT package repository" -r \
	$(dirname $temp_archive)
